# Generated by Django 3.0.5 on 2020-04-28 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('country_cod', models.CharField(max_length=2)),
                ('phone', models.CharField(max_length=10)),
                ('username', models.TextField()),
                ('userid', models.TextField()),
            ],
        ),
    ]
