# Generated by Django 3.0.5 on 2020-04-28 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginout', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdetails',
            old_name='country_cod',
            new_name='country_code',
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='email',
            field=models.EmailField(max_length=25),
        ),
    ]
