# Generated by Django 3.0.5 on 2020-04-28 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginout', '0002_auto_20200428_1635'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetails',
            name='userid',
        ),
    ]
