# Generated by Django 3.0.5 on 2020-04-28 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginout', '0003_remove_userdetails_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='country_code',
            field=models.CharField(max_length=2, null=True),
        ),
    ]
