# Generated by Django 3.0.5 on 2020-04-29 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginout', '0005_auto_20200428_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='email',
            field=models.EmailField(max_length=50),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='phone',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='username',
            field=models.CharField(max_length=50),
        ),
    ]
